name: Latest deploy

on: [workflow_dispatch]

jobs:
    deploy-image:
        name: Deploy the docker image
        runs-on: self-hosted

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Install aws-cli
              run: sudo apt install awscli
            
            - name: Configure AWS Creds
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}

            - name: Configure AWS credentials
              run: |
                aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws configure set region ${{ secrets.AWS_REGION }}

            - name: Retrieve ECR login credentials
              run: aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_REGISTRY_URL }}

            - name: Login to ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2

            - name: Stop old container
              run: sudo docker stop streaming_pipeline || true

            - name: Remove old container
              run: sudo docker rm streaming_pipeline || true
                
            - name: Pull new docker image
              run:  sudo docker pull ${{ steps.login-ecr.outputs.registry }}/${{ secrets.AWS_ECR_REPO }}:latest

            - name: Start the container
              run: sudo docker run -d --name streaming_pipeline ${{ steps.login-ecr.outputs.registry }}/${{ secrets.AWS_ECR_REPO }}:latest
